3 Datagrid vytvořených sestavení
peckadesign/CIServer pull request #5
Opened 2017-03-06 08:41 UTC by aloisjasa

#3 

- [x] výpis všech sestavení
- [x] proklik na detail
- [ ] řazení podle sloupců
- [ ] filtrování
- [ ] stránkování

2017-03-06 08:43 UTC, aloisjasa commented
Ahoj @MilanPala , mohl bych tě požádat o review?

2017-03-06 14:45 UTC, MilanPala requested changes
Podle mě dobré

2017-03-06 14:45 UTC, MilanPala commented on app/DashBoard/Controls/CreateTestServerDataGrid/Cells.latte
> +{define row-actions	}
nějaký úlet

2017-03-06 14:45 UTC, MilanPala commented on app/DashBoard/Controls/CreateTestServerDataGrid/Cells.latte
> +		{$cell|date:'j. n. Y H:i:s'}
Filtr pro výpis datumu jsem už použil ve dvou komponentách. Už by to stálo za přidání do globálních filtrů, aby byly všude

2017-03-06 14:45 UTC, MilanPala commented on app/DashBoard/Controls/CreateTestServerDataGrid/Control.php
> +	public function __construct(
Konstruktor prosím na první místo

2017-03-06 14:45 UTC, MilanPala commented on app/DashBoard/Controls/CreateTestServerDataGrid/Control.php
> +		$grid->addColumn( 'repository', 'Projekt' )->enableSort();
Tuhle syntaxi s mezerami myslím nepoužíváme: https://github.com/peckadesign/pecka/wiki/Coding-standard

2017-03-06 14:45 UTC, MilanPala commented on app/DashBoard/Presenters/templates/CreateTestServer/list.latte
> +	List vytvoření testovacích serverů
Místo `List` bych dal `Přehled` nebo `Výpis`

2017-03-06 15:08 UTC, aloisjasa commented on app/DashBoard/Presenters/templates/CreateTestServer/list.latte
> +	List vytvoření testovacích serverů
Upraveno na `Přehled`

2017-03-06 15:08 UTC, aloisjasa commented on app/DashBoard/Controls/CreateTestServerDataGrid/Control.php
> +	public function __construct(
Opraveno

2017-03-06 15:08 UTC, aloisjasa commented on app/DashBoard/Controls/CreateTestServerDataGrid/Cells.latte
> +{define row-actions	}
Opraveno (propašoval jsem do commitu tab)

2017-03-07 06:34 UTC, aloisjasa commented on app/DashBoard/Controls/CreateTestServerDataGrid/Cells.latte
> +		{$cell|date:'j. n. Y H:i:s'}
Vytvořena třída `CI\Utils\Helpers` v adresáři `app\Utils`. 
Tím namespacem a zařazením správně do adresářové struktury si nejsem jistý.

2017-03-07 06:35 UTC, aloisjasa commented
Ahoj @MilanPala , přepracováno podle připomínek. Mohl bych tě požádat o review?

2017-03-09 13:00 UTC, MilanPala commented
@aloisjasa Pěkné. Bylo by možné přeložit ty texty Prev/Next?

2017-03-09 14:06 UTC, aloisjasa commented
@MilanPala přeloženy i další prvky datagridu, plus ošetřen vstup pro helper dateTime

2017-03-09 15:17 UTC, MilanPala requested changes

2017-03-09 15:17 UTC, MilanPala commented on app/Utils/Helpers.php
> +		return $s instanceof \DateTime ? $s->format('j. n. Y H:i:s') : $s;
Úplně nejvís správně by zde měla být závislost na `\DateTimeInterface`, aby to příjmalo i `\DateTimeImmutable`

2017-03-10 06:50 UTC, aloisjasa commented on app/Utils/Helpers.php
> +		return $s instanceof \DateTime ? $s->format('j. n. Y H:i:s') : $s;
Je to tam.

2017-03-10 07:07 UTC, MilanPala approved these changes

2017-03-10 07:07 UTC, merged